"""Expanded HS-6 scenario families."""

from __future__ import annotations

from .models import ModbusTransaction, ScenarioProfile
from .profile_common import (
    COMMON_LIMITATIONS,
    FIELD_POINTS,
    NODES,
    float32_registers,
    tx,
)

MAINTENANCE_TRANSACTIONS: tuple[ModbusTransaction, ...] = (
    tx(1, 0, "hmi", 4, "read_input_registers", 0, 12, "", "ok", "pre_maintenance_poll"),
    tx(
        2,
        300,
        "maintenance",
        3,
        "read_holding_registers",
        200,
        6,
        "",
        "ok",
        "maintenance_precheck",
    ),
    tx(
        3,
        600,
        "maintenance",
        6,
        "write_single_register",
        200,
        1,
        "target=chlorine_sensor",
        "ok",
        "maintenance_select_target",
        wire_values=(4,),
    ),
    tx(
        4,
        900,
        "maintenance",
        6,
        "write_single_register",
        201,
        1,
        "action=recalibrate",
        "ok",
        "maintenance_select_action",
        wire_values=(2,),
    ),
    tx(
        5,
        1200,
        "maintenance",
        5,
        "write_single_coil",
        10,
        1,
        "trigger=true",
        "ok",
        "maintenance_trigger",
        wire_values=(1,),
    ),
    tx(
        6,
        1500,
        "maintenance",
        3,
        "read_holding_registers",
        210,
        4,
        "",
        "ok",
        "maintenance_status_check",
    ),
    tx(
        7,
        1800,
        "historian",
        4,
        "read_input_registers",
        0,
        16,
        "",
        "ok",
        "post_maintenance_poll",
    ),
)

PROCESS_FAULT_TRANSACTIONS: tuple[ModbusTransaction, ...] = (
    tx(1, 0, "historian", 4, "read_input_registers", 0, 16, "", "ok", "baseline_poll"),
    tx(
        2,
        250,
        "hmi",
        4,
        "read_input_registers",
        8,
        4,
        "",
        "ok",
        "chlorine_flow_review",
        "process_deviation_context",
    ),
    tx(
        3,
        500,
        "hmi",
        16,
        "write_multiple_registers",
        2,
        2,
        "chlorine_flow=0.1",
        "ok",
        "operator_low_dose_adjustment",
        "process_deviation_context",
        wire_values=float32_registers(0.1),
    ),
    tx(
        4, 750, "historian", 4, "read_input_registers", 0, 16, "", "ok", "followup_poll"
    ),
    tx(
        5,
        1000,
        "hmi",
        16,
        "write_multiple_registers",
        2,
        2,
        "chlorine_flow=0.8",
        "ok",
        "operator_corrective_adjustment",
        "process_deviation_context",
        wire_values=float32_registers(0.8),
    ),
    tx(
        6,
        1250,
        "historian",
        4,
        "read_input_registers",
        0,
        16,
        "",
        "ok",
        "stabilization_poll",
    ),
)

MISCONFIGURATION_TRANSACTIONS: tuple[ModbusTransaction, ...] = (
    tx(1, 0, "hmi", 4, "read_input_registers", 0, 12, "", "ok", "pre_change_poll"),
    tx(
        2,
        250,
        "maintenance",
        3,
        "read_holding_registers",
        0,
        8,
        "",
        "ok",
        "configuration_review",
    ),
    tx(
        3,
        500,
        "maintenance",
        16,
        "write_multiple_registers",
        4,
        2,
        "inlet_flow=0.0",
        "ok",
        "misconfiguration_candidate",
        "must_review",
        wire_values=float32_registers(0.0),
    ),
    tx(
        4,
        750,
        "maintenance",
        16,
        "write_multiple_registers",
        2,
        2,
        "chlorine_flow=2.5",
        "ok",
        "misconfiguration_candidate",
        "must_review",
        wire_values=float32_registers(2.5),
    ),
    tx(
        5,
        1000,
        "maintenance",
        6,
        "write_single_register",
        201,
        1,
        "action=unknown",
        "ok",
        "unexpected_maintenance_action",
        "must_review",
        wire_values=(99,),
    ),
    tx(6, 1250, "hmi", 4, "read_input_registers", 0, 16, "", "ok", "post_change_poll"),
)

NOISY_NETWORK_TRANSACTIONS: tuple[ModbusTransaction, ...] = (
    tx(1, 0, "historian", 4, "read_input_registers", 0, 16, "", "ok", "fast_poll"),
    tx(2, 80, "historian", 4, "read_input_registers", 0, 16, "", "ok", "fast_poll"),
    tx(3, 160, "hmi", 4, "read_input_registers", 0, 12, "", "ok", "operator_poll"),
    tx(4, 240, "historian", 4, "read_input_registers", 0, 16, "", "ok", "fast_poll"),
    tx(
        5,
        320,
        "unknown",
        3,
        "read_holding_registers",
        65000,
        2,
        "",
        "exception_0x02",
        "background_invalid_access",
        "exception_pattern",
    ),
    tx(6, 400, "historian", 4, "read_input_registers", 0, 16, "", "ok", "fast_poll"),
    tx(7, 480, "hmi", 4, "read_input_registers", 100, 3, "", "ok", "operator_poll"),
    tx(8, 560, "historian", 4, "read_input_registers", 0, 16, "", "ok", "fast_poll"),
)

DEGRADED_TRANSACTIONS: tuple[ModbusTransaction, ...] = (
    tx(1, 0, "hmi", 4, "read_input_registers", 0, 12, "", "ok", "degraded_start_poll"),
    tx(2, 400, "historian", 4, "read_input_registers", 0, 16, "", "ok", "slow_poll"),
    tx(
        3,
        1200,
        "hmi",
        16,
        "write_multiple_registers",
        4,
        2,
        "inlet_flow=3.5",
        "ok",
        "reduced_flow_mode",
        "process_deviation_context",
        wire_values=float32_registers(3.5),
    ),
    tx(4, 2200, "historian", 4, "read_input_registers", 0, 16, "", "ok", "slow_poll"),
    tx(
        5,
        3200,
        "maintenance",
        3,
        "read_holding_registers",
        200,
        4,
        "",
        "ok",
        "degraded_maintenance_check",
    ),
    tx(
        6,
        4200,
        "hmi",
        16,
        "write_multiple_registers",
        2,
        2,
        "chlorine_flow=0.2",
        "ok",
        "reduced_dosing_mode",
        "process_deviation_context",
        wire_values=float32_registers(0.2),
    ),
)

EXPANDED_SCENARIOS: tuple[ScenarioProfile, ...] = (
    ScenarioProfile(
        "MVP-MB-HYDRA-005",
        "HydraSim planned maintenance window",
        "Maintenance-only command sequence with before and after process polling.",
        NODES,
        FIELD_POINTS,
        MAINTENANCE_TRANSACTIONS,
        COMMON_LIMITATIONS
        + (
            "Maintenance actions are simulated workflow behavior, not field validation.",
        ),
    ),
    ScenarioProfile(
        "MVP-MB-HYDRA-006",
        "HydraSim abnormal process response scenario",
        "Process-deviation context with corrective operator adjustments.",
        NODES,
        FIELD_POINTS,
        PROCESS_FAULT_TRANSACTIONS,
        COMMON_LIMITATIONS
        + (
            "Process-deviation labels are synthetic scenario context, not safety impact.",
        ),
    ),
    ScenarioProfile(
        "MVP-MB-HYDRA-007",
        "HydraSim misconfiguration review scenario",
        "Configuration-like writes that deserve review without implying intent.",
        NODES,
        FIELD_POINTS,
        MISCONFIGURATION_TRANSACTIONS,
        COMMON_LIMITATIONS
        + (
            "Misconfiguration labels are synthetic review prompts, not confirmed error.",
        ),
    ),
    ScenarioProfile(
        "MVP-MB-HYDRA-008",
        "HydraSim noisy Modbus polling scenario",
        "High-chatter polling and invalid-access noise for coverage review.",
        NODES,
        FIELD_POINTS,
        NOISY_NETWORK_TRANSACTIONS,
        COMMON_LIMITATIONS
        + (
            "Noisy-network behavior is modeled as Modbus chatter, not packet loss.",
            "Exception responses are synthetic coverage signals, not incident claims.",
        ),
    ),
    ScenarioProfile(
        "MVP-MB-HYDRA-009",
        "HydraSim degraded operations scenario",
        "Lower-rate polling and reduced setpoints representing degraded-mode context.",
        NODES,
        FIELD_POINTS,
        DEGRADED_TRANSACTIONS,
        COMMON_LIMITATIONS
        + ("Degraded-mode labels are scenario context, not proof of plant state.",),
    ),
)
