"""Review, noisy-polling, and failover scenario definitions."""

from __future__ import annotations

from .models import HsScenario
from .scenario_base import COMMON_LIMITATIONS, tx

REVIEW_SCENARIOS: tuple[HsScenario, ...] = (
    HsScenario(
        "HS-WTP-010",
        "Unknown workstation review",
        "Unknown workstation range reads and writes that deserve review.",
        ("supervisory",),
        ("dosing", "disinfection"),
        (
            tx(
                1,
                0,
                "engineering-workstation",
                "dosing-plc",
                "supervisory",
                "dosing",
                3,
                "read_holding_registers",
                0,
                4,
                "",
                "ok",
                "range_read",
                "enumeration_like",
            ),
            tx(
                2,
                250,
                "engineering-workstation",
                "dosing-plc",
                "supervisory",
                "dosing",
                3,
                "read_holding_registers",
                50,
                4,
                "",
                "ok",
                "range_read",
                "enumeration_like",
            ),
            tx(
                3,
                500,
                "engineering-workstation",
                "disinfection-plc",
                "supervisory",
                "disinfection",
                6,
                "write_single_register",
                201,
                1,
                "action=7",
                "ok",
                "unexpected_write",
                "must_review",
                (7,),
            ),
        ),
        COMMON_LIMITATIONS
        + ("Unknown-workstation behavior is a review prompt, not attribution.",),
    ),
    HsScenario(
        "HS-WTP-011",
        "Noisy polling",
        "High-chatter historian/HMI polling and invalid-access noise.",
        ("supervisory",),
        ("intake", "dosing", "disinfection"),
        (
            tx(
                1,
                0,
                "plant-historian",
                "intake-plc",
                "supervisory",
                "intake",
                4,
                "read_input_registers",
                0,
                8,
                "",
                "ok",
                "fast_poll",
            ),
            tx(
                2,
                80,
                "plant-historian",
                "dosing-plc",
                "supervisory",
                "dosing",
                4,
                "read_input_registers",
                0,
                8,
                "",
                "ok",
                "fast_poll",
            ),
            tx(
                3,
                160,
                "plant-historian",
                "disinfection-plc",
                "supervisory",
                "disinfection",
                4,
                "read_input_registers",
                0,
                8,
                "",
                "ok",
                "fast_poll",
            ),
            tx(
                4,
                240,
                "scada-hmi",
                "dosing-plc",
                "supervisory",
                "dosing",
                3,
                "read_holding_registers",
                65000,
                2,
                "",
                "exception_0x02",
                "invalid_access_noise",
                "exception_pattern",
            ),
        ),
        COMMON_LIMITATIONS
        + ("Noisy polling is modeled as traffic chatter, not network impairment.",),
    ),
    HsScenario(
        "HS-WTP-012",
        "Controller failover context",
        "Controller status polling and alternate-controller review traffic.",
        ("field-controllers", "supervisory"),
        ("intake", "dosing"),
        (
            tx(
                1,
                0,
                "scada-hmi",
                "intake-plc",
                "supervisory",
                "intake",
                4,
                "read_input_registers",
                100,
                4,
                "",
                "ok",
                "primary_controller_poll",
            ),
            tx(
                2,
                250,
                "scada-hmi",
                "dosing-plc",
                "supervisory",
                "dosing",
                4,
                "read_input_registers",
                100,
                4,
                "",
                "ok",
                "alternate_controller_poll",
                "failover_context",
            ),
            tx(
                3,
                500,
                "dosing-plc",
                "dosing-pump-ao",
                "field-controllers",
                "dosing",
                6,
                "write_single_register",
                8,
                1,
                "manual_mode=1",
                "ok",
                "manual_mode_context",
                "must_review",
                (1,),
            ),
        ),
        COMMON_LIMITATIONS
        + ("Failover labels are synthetic context, not availability evidence.",),
    ),
)
