"""Fault, deviation, and plant-action scenario definitions."""

from __future__ import annotations

from .models import HsScenario
from .scenario_base import COMMON_LIMITATIONS, float32_words, tx

FAULT_SCENARIOS: tuple[HsScenario, ...] = (
    HsScenario(
        "HS-WTP-005",
        "Pump failure context",
        "Pumping-area reduced-response and alarm-context traffic.",
        ("field-controllers", "supervisory"),
        ("storage-pumping",),
        (
            tx(
                1,
                0,
                "pumping-plc",
                "clearwell-level-ai",
                "field-controllers",
                "storage-pumping",
                4,
                "read_input_registers",
                0,
                2,
                "",
                "ok",
                "level_poll",
            ),
            tx(
                2,
                250,
                "pumping-plc",
                "finished-water-pump-ao",
                "field-controllers",
                "storage-pumping",
                6,
                "write_single_register",
                8,
                1,
                "pump_speed=0",
                "ok",
                "pump_failure_context",
                "must_review",
                (0,),
            ),
            tx(
                3,
                500,
                "scada-hmi",
                "pumping-plc",
                "supervisory",
                "storage-pumping",
                4,
                "read_input_registers",
                100,
                4,
                "",
                "ok",
                "alarm_context_poll",
                "process_deviation_context",
            ),
        ),
        COMMON_LIMITATIONS
        + ("Pump-failure labels are synthetic and not a real equipment diagnosis.",),
    ),
    HsScenario(
        "HS-WTP-006",
        "Sensor drift context",
        "Repeated polling with drift-context labels for one analyzer path.",
        ("field-controllers", "supervisory"),
        ("disinfection",),
        (
            tx(
                1,
                0,
                "disinfection-plc",
                "chlorine-analyzer-ai",
                "field-controllers",
                "disinfection",
                4,
                "read_input_registers",
                0,
                2,
                "",
                "ok",
                "baseline_poll",
            ),
            tx(
                2,
                500,
                "disinfection-plc",
                "chlorine-analyzer-ai",
                "field-controllers",
                "disinfection",
                4,
                "read_input_registers",
                0,
                2,
                "",
                "ok",
                "drift_context_poll",
                "sensor_drift_context",
            ),
            tx(
                3,
                1000,
                "plant-historian",
                "disinfection-plc",
                "supervisory",
                "disinfection",
                4,
                "read_input_registers",
                0,
                8,
                "",
                "ok",
                "historian_drift_review",
            ),
        ),
        COMMON_LIMITATIONS
        + ("Drift labels are simulated context, not calibration evidence.",),
    ),
    HsScenario(
        "HS-WTP-007",
        "Analyzer fault context",
        "Analyzer exception and follow-up polling context.",
        ("field-controllers", "supervisory"),
        ("dosing",),
        (
            tx(
                1,
                0,
                "dosing-plc",
                "dosing-ph-ai",
                "field-controllers",
                "dosing",
                4,
                "read_input_registers",
                65000,
                2,
                "",
                "exception_0x02",
                "analyzer_exception",
                "exception_pattern",
            ),
            tx(
                2,
                250,
                "scada-hmi",
                "dosing-plc",
                "supervisory",
                "dosing",
                4,
                "read_input_registers",
                100,
                4,
                "",
                "ok",
                "alarm_context_poll",
            ),
        ),
        COMMON_LIMITATIONS
        + ("Exception responses are synthetic coverage signals, not failure proof.",),
    ),
    HsScenario(
        "HS-WTP-008",
        "Filter backwash",
        "Filtration backwash command and follow-up polling context.",
        ("field-controllers", "supervisory"),
        ("filtration",),
        (
            tx(
                1,
                0,
                "filtration-plc",
                "filter-dp-ai",
                "field-controllers",
                "filtration",
                4,
                "read_input_registers",
                0,
                2,
                "",
                "ok",
                "dp_poll",
            ),
            tx(
                2,
                250,
                "filtration-plc",
                "filter-backwash-ao",
                "field-controllers",
                "filtration",
                5,
                "write_single_coil",
                10,
                1,
                "backwash=true",
                "ok",
                "backwash_command",
                "must_review",
                (1,),
            ),
            tx(
                3,
                500,
                "plant-historian",
                "filtration-plc",
                "supervisory",
                "filtration",
                4,
                "read_input_registers",
                0,
                8,
                "",
                "ok",
                "backwash_followup_poll",
            ),
        ),
        COMMON_LIMITATIONS
        + ("Backwash labels are scenario context, not operating procedure evidence.",),
    ),
    HsScenario(
        "HS-WTP-009",
        "Disinfection excursion",
        "Disinfection-area review context with corrective dosing writes.",
        ("field-controllers", "supervisory"),
        ("disinfection",),
        (
            tx(
                1,
                0,
                "disinfection-plc",
                "chlorine-analyzer-ai",
                "field-controllers",
                "disinfection",
                4,
                "read_input_registers",
                0,
                2,
                "",
                "ok",
                "chlorine_review",
                "process_deviation_context",
            ),
            tx(
                2,
                250,
                "disinfection-plc",
                "chlorine-pump-ao",
                "field-controllers",
                "disinfection",
                16,
                "write_multiple_registers",
                2,
                2,
                "chlorine_rate=0.65",
                "ok",
                "corrective_chlorine_write",
                "process_deviation_context",
                float32_words(0.65),
            ),
            tx(
                3,
                500,
                "scada-hmi",
                "disinfection-plc",
                "supervisory",
                "disinfection",
                3,
                "read_holding_registers",
                0,
                6,
                "",
                "ok",
                "operator_review",
            ),
        ),
        COMMON_LIMITATIONS
        + ("Excursion labels are simulated context, not compliance evidence.",),
    ),
)
