"""Bounded CFD and digital-twin primitives.

The package provides small deterministic finite-volume building blocks for the
HydraSim reference water-treatment plant. It is not a calibrated plant-design
solver by itself.
"""

from .area_models import AREA_IDS, AreaCfdModel, reference_area_model
from .boundary_conditions import (
    BoundaryConditionContract,
    boundary_condition_catalog,
    boundary_condition_ids,
    conditions_for_geometry,
    get_boundary_condition,
)
from .calibration_evidence import (
    CalibrationDataPoint,
    CalibrationEvidenceFit,
    RejectedCalibrationData,
    assess_calibration_fit,
    fit_calibration_parameter,
)
from .controller_coupling import (
    ControllerCouplingAction,
    ControllerCouplingContract,
    apply_controller_action_to_scalar,
    controller_contracts_for_actuators,
    controller_coupling_catalog,
    evaluate_controller_action,
)
from .digital_twin import (
    CalibrationAssessment,
    CalibrationConfidence,
    CalibrationEvidenceClass,
    CalibrationEvidenceSource,
    CalibrationParameter,
    CalibrationRecord,
    CalibrationResidual,
    CalibrationStatus,
    DigitalTwinMetadata,
    TwinStatus,
    UncertaintyRecord,
    assess_calibration_evidence,
    build_reference_calibration_assessment,
    evaluate_calibration_residual,
)
from .evidence.external_review import (
    ExternalReviewCalibrationGate,
    ExternalReviewEvidenceRecord,
    build_external_review_calibration_gate,
    render_external_review_calibration_gate_json,
)
from .device_coupling import (
    ActuatorCouplingContract,
    SamplingRegion,
    SensorCouplingContract,
    apply_scalar_source_region,
    actuator_contracts_for_unit,
    device_coupling_catalog,
    sample_scalar_region,
    sensor_contracts_for_unit,
)
from .export import export_cfd_summary
from .fields import FlowField, ScalarField
from .mesh import BoundaryPatch, Obstacle, StructuredMesh, create_rectangular_mesh
from .operator_semantics import (
    EngineeringWorkstationEvent,
    HistorianTrendTag,
    MaintenanceWindow,
    OperatorActionRecord,
    OperatorHistorianSemanticBundle,
    SupervisoryAlarmState,
    build_historian_trend_tags,
    build_reference_operator_historian_semantics,
    derive_alarm_state,
)
from .performance import (
    CfdBenchmarkResult,
    CfdPerformancePreset,
    CfdRuntimePerformanceBudget,
    CfdRuntimePerformanceGateRecord,
    build_runtime_performance_gate,
    estimate_field_memory_bytes,
    get_performance_preset,
    get_runtime_performance_budget,
    mesh_for_preset,
    performance_preset_ids,
    performance_presets,
    render_runtime_performance_gate_json,
    run_cfd_benchmark,
    runtime_performance_budgets,
)
from .scalar import ScalarTransportConfig, ScalarTransportResult, step_scalar_transport
from .solver import FlowSolverConfig, FlowStepResult, initialize_flow, solve_flow_step
from .supervisory import (
    SupervisoryProfile,
    SupervisoryTwinRecord,
    build_reference_supervisory_records,
    build_supervisory_records,
    supervisory_profile_catalog,
    supervisory_profile_ids,
)
from .turbulence import MixingModelConfig, effective_diffusivity
from .unit_processes import (
    InstrumentationPoint,
    ProcessBoundary,
    UnitProcess,
    get_unit_process,
    unit_process_catalog,
    unit_process_ids,
    units_by_area,
)
from .evidence.validation import (
    EXTERNAL_COMPARISON_NOT_VALIDATION,
    REAL_PLANT_VALIDATION_BLOCKED,
    DigitalTwinValidationAreaRecord,
    DigitalTwinValidationGate,
    ExternalCfdComparisonRecord,
    build_digital_twin_validation_gate,
    build_reference_validation_area_records,
    render_digital_twin_validation_gate_json,
)
from .verification import (
    NumericalVerificationResult,
    NumericalVerificationSuite,
    build_reference_numerical_verification_suite,
    verify_boundary_condition_response,
    verify_constant_scalar_conservation,
    verify_flow_mass_residual_bound,
    verify_long_run_scalar_drift,
    verify_mesh_refinement_sensitivity,
)

__all__ = [
    "AREA_IDS",
    "ActuatorCouplingContract",
    "AreaCfdModel",
    "BoundaryConditionContract",
    "BoundaryPatch",
    "CfdBenchmarkResult",
    "CfdPerformancePreset",
    "CfdRuntimePerformanceBudget",
    "CfdRuntimePerformanceGateRecord",
    "CalibrationAssessment",
    "CalibrationDataPoint",
    "CalibrationConfidence",
    "CalibrationEvidenceClass",
    "CalibrationEvidenceFit",
    "CalibrationEvidenceSource",
    "CalibrationParameter",
    "CalibrationRecord",
    "CalibrationResidual",
    "CalibrationStatus",
    "ControllerCouplingAction",
    "ControllerCouplingContract",
    "DigitalTwinMetadata",
    "DigitalTwinValidationAreaRecord",
    "DigitalTwinValidationGate",
    "EXTERNAL_COMPARISON_NOT_VALIDATION",
    "EngineeringWorkstationEvent",
    "ExternalCfdComparisonRecord",
    "ExternalReviewCalibrationGate",
    "ExternalReviewEvidenceRecord",
    "FlowField",
    "FlowSolverConfig",
    "FlowStepResult",
    "HistorianTrendTag",
    "InstrumentationPoint",
    "MaintenanceWindow",
    "MixingModelConfig",
    "NumericalVerificationResult",
    "NumericalVerificationSuite",
    "Obstacle",
    "OperatorActionRecord",
    "OperatorHistorianSemanticBundle",
    "ProcessBoundary",
    "REAL_PLANT_VALIDATION_BLOCKED",
    "RejectedCalibrationData",
    "ScalarField",
    "ScalarTransportConfig",
    "ScalarTransportResult",
    "SamplingRegion",
    "SensorCouplingContract",
    "StructuredMesh",
    "SupervisoryAlarmState",
    "SupervisoryProfile",
    "SupervisoryTwinRecord",
    "TwinStatus",
    "UnitProcess",
    "UncertaintyRecord",
    "create_rectangular_mesh",
    "actuator_contracts_for_unit",
    "assess_calibration_fit",
    "assess_calibration_evidence",
    "apply_controller_action_to_scalar",
    "apply_scalar_source_region",
    "boundary_condition_catalog",
    "boundary_condition_ids",
    "build_historian_trend_tags",
    "build_reference_calibration_assessment",
    "build_reference_validation_area_records",
    "build_digital_twin_validation_gate",
    "build_external_review_calibration_gate",
    "build_reference_operator_historian_semantics",
    "build_reference_numerical_verification_suite",
    "build_reference_supervisory_records",
    "build_supervisory_records",
    "build_runtime_performance_gate",
    "conditions_for_geometry",
    "controller_contracts_for_actuators",
    "controller_coupling_catalog",
    "device_coupling_catalog",
    "derive_alarm_state",
    "effective_diffusivity",
    "evaluate_controller_action",
    "evaluate_calibration_residual",
    "export_cfd_summary",
    "estimate_field_memory_bytes",
    "fit_calibration_parameter",
    "get_boundary_condition",
    "get_performance_preset",
    "get_runtime_performance_budget",
    "get_unit_process",
    "initialize_flow",
    "mesh_for_preset",
    "performance_preset_ids",
    "performance_presets",
    "reference_area_model",
    "render_runtime_performance_gate_json",
    "render_digital_twin_validation_gate_json",
    "render_external_review_calibration_gate_json",
    "run_cfd_benchmark",
    "runtime_performance_budgets",
    "sample_scalar_region",
    "sensor_contracts_for_unit",
    "solve_flow_step",
    "step_scalar_transport",
    "supervisory_profile_catalog",
    "supervisory_profile_ids",
    "unit_process_catalog",
    "unit_process_ids",
    "units_by_area",
    "verify_boundary_condition_response",
    "verify_constant_scalar_conservation",
    "verify_flow_mass_residual_bound",
    "verify_long_run_scalar_drift",
    "verify_mesh_refinement_sensitivity",
]
